/**
 * 아이랑 세종 AI - 시범 데이터
 *
 * 본 데이터는 시연용 모의 데이터입니다.
 * 실제 운영 시에는 담당부서 확인 후 월 1회 갱신하며, 공식 페이지로 최종 안내합니다.
 */

const DATA_UPDATED = "2026-05-15";

// 생활권 목록 (1단계 시범 대상)
const DISTRICTS = [
  "도담동", "아름동", "종촌동", "고운동", "새롬동",
  "다정동", "보람동", "소담동", "반곡동", "한솔동",
  "어진동", "나성동", "대평동"
];

// 시설 데이터
// managed: 세종시 직접 관리 여부 (true=표준 정보표 관리, false=공식 링크 안내)
const FACILITIES = [
  {
    id: 1,
    name: "도담동 복합커뮤니티센터",
    category: "복합커뮤니티센터",
    district: "도담동",
    address: "세종특별자치시 도움5로 11",
    managed: true,
    hours: { weekday: "09:00-22:00", weekend: "09:00-18:00", note: "주민자치 공간은 별도 운영" },
    closedDays: ["1월 1일", "설·추석 당일"],
    reservation: false,
    indoor: true,
    facilities: { nursing: true, diaper: true, washingHotWater: true },
    accessibility: { stroller: true, twinStroller: true, elevator: true, ramp: true },
    parking: { available: true, indoor: true, capacity: 80 },
    cost: { free: true },
    ageRange: [0, 36],
    crowdedness: { weekday: "low", weekend: "mid" },
    weatherAdapt: { rain: "good", heat: "good", cold: "good", dust: "good" },
    description: "도서관·체육·문화시설이 한 건물에 있어 영유아 동반 외출에 적합합니다.",
    officialUrl: "https://www.sejong.go.kr/",
    updatedAt: DATA_UPDATED,
  },
  {
    id: 2,
    name: "아름동 복합커뮤니티센터",
    category: "복합커뮤니티센터",
    district: "아름동",
    address: "세종특별자치시 아름서길 27",
    managed: true,
    hours: { weekday: "09:00-22:00", weekend: "09:00-18:00" },
    closedDays: ["1월 1일", "설·추석 당일"],
    reservation: false,
    indoor: true,
    facilities: { nursing: true, diaper: true, washingHotWater: true },
    accessibility: { stroller: true, twinStroller: true, elevator: true, ramp: true },
    parking: { available: true, indoor: true, capacity: 70 },
    cost: { free: true },
    ageRange: [0, 36],
    crowdedness: { weekday: "low", weekend: "high" },
    weatherAdapt: { rain: "good", heat: "good", cold: "good", dust: "good" },
    description: "어린이도서관과 다목적실이 함께 있어 우천·폭염 시 머물기 좋습니다.",
    officialUrl: "https://www.sejong.go.kr/",
    updatedAt: DATA_UPDATED,
  },
  {
    id: 3,
    name: "종촌동 복합커뮤니티센터",
    category: "복합커뮤니티센터",
    district: "종촌동",
    address: "세종특별자치시 절재로 154",
    managed: true,
    hours: { weekday: "09:00-22:00", weekend: "09:00-18:00" },
    closedDays: ["1월 1일", "설·추석 당일"],
    reservation: false,
    indoor: true,
    facilities: { nursing: true, diaper: true, washingHotWater: false },
    accessibility: { stroller: true, twinStroller: true, elevator: true, ramp: true },
    parking: { available: true, indoor: true, capacity: 60 },
    cost: { free: true },
    ageRange: [0, 36],
    crowdedness: { weekday: "low", weekend: "mid" },
    weatherAdapt: { rain: "good", heat: "good", cold: "good", dust: "good" },
    description: "장난감도서관이 인접해 영유아 가정 이용이 많습니다.",
    officialUrl: "https://www.sejong.go.kr/",
    updatedAt: DATA_UPDATED,
  },
  {
    id: 4,
    name: "고운동 복합커뮤니티센터",
    category: "복합커뮤니티센터",
    district: "고운동",
    address: "세종특별자치시 가름로 232",
    managed: true,
    hours: { weekday: "09:00-22:00", weekend: "09:00-18:00" },
    closedDays: ["1월 1일", "설·추석 당일"],
    reservation: false,
    indoor: true,
    facilities: { nursing: true, diaper: true, washingHotWater: true },
    accessibility: { stroller: true, twinStroller: true, elevator: true, ramp: true },
    parking: { available: true, indoor: true, capacity: 90 },
    cost: { free: true },
    ageRange: [0, 36],
    crowdedness: { weekday: "low", weekend: "high" },
    weatherAdapt: { rain: "good", heat: "good", cold: "good", dust: "good" },
    description: "넓은 광장과 실내 공간이 모두 있어 날씨와 무관하게 이용 가능합니다.",
    officialUrl: "https://www.sejong.go.kr/",
    updatedAt: DATA_UPDATED,
  },
  {
    id: 5,
    name: "새롬동 복합커뮤니티센터",
    category: "복합커뮤니티센터",
    district: "새롬동",
    address: "세종특별자치시 새롬중앙로 84",
    managed: true,
    hours: { weekday: "09:00-22:00", weekend: "09:00-18:00" },
    closedDays: ["1월 1일", "설·추석 당일"],
    reservation: false,
    indoor: true,
    facilities: { nursing: true, diaper: true, washingHotWater: true },
    accessibility: { stroller: true, twinStroller: true, elevator: true, ramp: true },
    parking: { available: true, indoor: true, capacity: 75 },
    cost: { free: true },
    ageRange: [0, 36],
    crowdedness: { weekday: "low", weekend: "mid" },
    weatherAdapt: { rain: "good", heat: "good", cold: "good", dust: "good" },
    description: "공동육아나눔터와 함께 이용 가능합니다.",
    officialUrl: "https://www.sejong.go.kr/",
    updatedAt: DATA_UPDATED,
  },
  {
    id: 6,
    name: "다정동 복합커뮤니티센터",
    category: "복합커뮤니티센터",
    district: "다정동",
    address: "세종특별자치시 다정북로 67",
    managed: true,
    hours: { weekday: "09:00-22:00", weekend: "09:00-18:00" },
    closedDays: ["1월 1일", "설·추석 당일"],
    reservation: false,
    indoor: true,
    facilities: { nursing: true, diaper: true, washingHotWater: false },
    accessibility: { stroller: true, twinStroller: true, elevator: true, ramp: true },
    parking: { available: true, indoor: true, capacity: 65 },
    cost: { free: true },
    ageRange: [0, 36],
    crowdedness: { weekday: "low", weekend: "mid" },
    weatherAdapt: { rain: "good", heat: "good", cold: "good", dust: "good" },
    description: "최근 개관한 시설로 영유아 편의시설 상태가 양호합니다.",
    officialUrl: "https://www.sejong.go.kr/",
    updatedAt: DATA_UPDATED,
  },
  {
    id: 7,
    name: "보람동 복합커뮤니티센터",
    category: "복합커뮤니티센터",
    district: "보람동",
    address: "세종특별자치시 보람북로 28",
    managed: true,
    hours: { weekday: "09:00-22:00", weekend: "09:00-18:00" },
    closedDays: ["1월 1일", "설·추석 당일"],
    reservation: false,
    indoor: true,
    facilities: { nursing: true, diaper: true, washingHotWater: true },
    accessibility: { stroller: true, twinStroller: true, elevator: true, ramp: true },
    parking: { available: true, indoor: true, capacity: 70 },
    cost: { free: true },
    ageRange: [0, 36],
    crowdedness: { weekday: "low", weekend: "mid" },
    weatherAdapt: { rain: "good", heat: "good", cold: "good", dust: "good" },
    description: "어진동·보람동 생활권 가족 이용이 많습니다.",
    officialUrl: "https://www.sejong.go.kr/",
    updatedAt: DATA_UPDATED,
  },
  {
    id: 8,
    name: "소담동 복합커뮤니티센터",
    category: "복합커뮤니티센터",
    district: "소담동",
    address: "세종특별자치시 소담1로 22",
    managed: true,
    hours: { weekday: "09:00-22:00", weekend: "09:00-18:00" },
    closedDays: ["1월 1일", "설·추석 당일"],
    reservation: false,
    indoor: true,
    facilities: { nursing: true, diaper: true, washingHotWater: false },
    accessibility: { stroller: true, twinStroller: true, elevator: true, ramp: true },
    parking: { available: true, indoor: true, capacity: 60 },
    cost: { free: true },
    ageRange: [0, 36],
    crowdedness: { weekday: "low", weekend: "low" },
    weatherAdapt: { rain: "good", heat: "good", cold: "good", dust: "good" },
    description: "비교적 한산하여 영아 동반 외출에 부담이 적습니다.",
    officialUrl: "https://www.sejong.go.kr/",
    updatedAt: DATA_UPDATED,
  },
  {
    id: 9,
    name: "반곡동 복합커뮤니티센터",
    category: "복합커뮤니티센터",
    district: "반곡동",
    address: "세종특별자치시 반곡중앙로 89",
    managed: true,
    hours: { weekday: "09:00-22:00", weekend: "09:00-18:00" },
    closedDays: ["1월 1일", "설·추석 당일"],
    reservation: false,
    indoor: true,
    facilities: { nursing: true, diaper: true, washingHotWater: true },
    accessibility: { stroller: true, twinStroller: true, elevator: true, ramp: true },
    parking: { available: true, indoor: true, capacity: 80 },
    cost: { free: true },
    ageRange: [0, 36],
    crowdedness: { weekday: "low", weekend: "mid" },
    weatherAdapt: { rain: "good", heat: "good", cold: "good", dust: "good" },
    description: "신규 입주지역에 위치하여 영유아 가구 비중이 높습니다.",
    officialUrl: "https://www.sejong.go.kr/",
    updatedAt: DATA_UPDATED,
  },
  {
    id: 10,
    name: "한솔동 복합커뮤니티센터",
    category: "복합커뮤니티센터",
    district: "한솔동",
    address: "세종특별자치시 한누리대로 411",
    managed: true,
    hours: { weekday: "09:00-22:00", weekend: "09:00-18:00" },
    closedDays: ["1월 1일", "설·추석 당일"],
    reservation: false,
    indoor: true,
    facilities: { nursing: true, diaper: true, washingHotWater: false },
    accessibility: { stroller: true, twinStroller: false, elevator: true, ramp: true },
    parking: { available: true, indoor: false, capacity: 40 },
    cost: { free: true },
    ageRange: [0, 36],
    crowdedness: { weekday: "low", weekend: "mid" },
    weatherAdapt: { rain: "good", heat: "good", cold: "good", dust: "good" },
    description: "초기 조성지역으로 출입 동선이 다소 좁아 광폭 유모차는 사전 확인 권장.",
    officialUrl: "https://www.sejong.go.kr/",
    updatedAt: DATA_UPDATED,
  },

  // --- 도서관 ---
  {
    id: 11,
    name: "도담동 시립도서관 영유아실",
    category: "도서관",
    district: "도담동",
    address: "세종특별자치시 도움5로 11",
    managed: true,
    hours: { weekday: "09:00-22:00", weekend: "09:00-17:00" },
    closedDays: ["매주 월요일", "1월 1일", "설·추석 당일"],
    reservation: false,
    indoor: true,
    facilities: { nursing: true, diaper: true, washingHotWater: false },
    accessibility: { stroller: true, twinStroller: true, elevator: true, ramp: true },
    parking: { available: true, indoor: true, capacity: 80 },
    cost: { free: true },
    ageRange: [0, 36],
    crowdedness: { weekday: "low", weekend: "high" },
    weatherAdapt: { rain: "good", heat: "good", cold: "good", dust: "good" },
    description: "영유아 전용 공간과 그림책 구역이 분리되어 있어 조용히 머물기 좋습니다.",
    officialUrl: "https://www.sejong.go.kr/lib.do",
    updatedAt: DATA_UPDATED,
  },
  {
    id: 12,
    name: "새롬동 시립도서관 영유아실",
    category: "도서관",
    district: "새롬동",
    address: "세종특별자치시 새롬중앙로 84",
    managed: true,
    hours: { weekday: "09:00-22:00", weekend: "09:00-17:00" },
    closedDays: ["매주 월요일", "1월 1일", "설·추석 당일"],
    reservation: false,
    indoor: true,
    facilities: { nursing: true, diaper: true, washingHotWater: false },
    accessibility: { stroller: true, twinStroller: true, elevator: true, ramp: true },
    parking: { available: true, indoor: true, capacity: 75 },
    cost: { free: true },
    ageRange: [0, 36],
    crowdedness: { weekday: "low", weekend: "mid" },
    weatherAdapt: { rain: "good", heat: "good", cold: "good", dust: "good" },
    description: "그림책 읽기 프로그램을 정기 운영합니다.",
    officialUrl: "https://www.sejong.go.kr/lib.do",
    updatedAt: DATA_UPDATED,
  },
  {
    id: 13,
    name: "고운동 시립도서관 영유아실",
    category: "도서관",
    district: "고운동",
    address: "세종특별자치시 가름로 232",
    managed: true,
    hours: { weekday: "09:00-22:00", weekend: "09:00-17:00" },
    closedDays: ["매주 월요일", "1월 1일", "설·추석 당일"],
    reservation: false,
    indoor: true,
    facilities: { nursing: true, diaper: true, washingHotWater: false },
    accessibility: { stroller: true, twinStroller: true, elevator: true, ramp: true },
    parking: { available: true, indoor: true, capacity: 90 },
    cost: { free: true },
    ageRange: [0, 36],
    crowdedness: { weekday: "low", weekend: "mid" },
    weatherAdapt: { rain: "good", heat: "good", cold: "good", dust: "good" },
    description: "넓은 영유아 공간과 다양한 그림책 보유.",
    officialUrl: "https://www.sejong.go.kr/lib.do",
    updatedAt: DATA_UPDATED,
  },
  {
    id: 14,
    name: "국립세종도서관 어린이자료실",
    category: "도서관",
    district: "어진동",
    address: "세종특별자치시 다솜3로 48",
    managed: false,
    hours: { weekday: "09:00-18:00", weekend: "09:00-18:00" },
    closedDays: ["매월 둘째·넷째 월요일", "1월 1일", "설·추석 당일"],
    reservation: false,
    indoor: true,
    facilities: { nursing: true, diaper: true, washingHotWater: false },
    accessibility: { stroller: true, twinStroller: true, elevator: true, ramp: true },
    parking: { available: true, indoor: true, capacity: 200 },
    cost: { free: true },
    ageRange: [6, 36],
    crowdedness: { weekday: "mid", weekend: "high" },
    weatherAdapt: { rain: "good", heat: "good", cold: "good", dust: "good" },
    description: "국립도서관 직영 시설입니다. 세종시 직접 관리 대상은 아니며 공식 페이지로 안내합니다.",
    officialUrl: "https://sejong.nl.go.kr/",
    updatedAt: DATA_UPDATED,
  },

  // --- 공동육아나눔터 ---
  {
    id: 15,
    name: "도담동 공동육아나눔터",
    category: "공동육아나눔터",
    district: "도담동",
    address: "세종특별자치시 도움5로 11",
    managed: true,
    hours: { weekday: "10:00-17:00", weekend: "휴무" },
    closedDays: ["토요일", "일요일", "법정공휴일"],
    reservation: true,
    indoor: true,
    facilities: { nursing: true, diaper: true, washingHotWater: true },
    accessibility: { stroller: true, twinStroller: true, elevator: true, ramp: true },
    parking: { available: true, indoor: true, capacity: 80 },
    cost: { free: true },
    ageRange: [0, 36],
    crowdedness: { weekday: "mid", weekend: "n/a" },
    weatherAdapt: { rain: "good", heat: "good", cold: "good", dust: "good" },
    description: "예약제로 운영되며 영유아 보호자 교류 프로그램을 함께 운영합니다.",
    officialUrl: "https://sejong.familynet.or.kr/",
    updatedAt: DATA_UPDATED,
  },
  {
    id: 16,
    name: "고운동 공동육아나눔터",
    category: "공동육아나눔터",
    district: "고운동",
    address: "세종특별자치시 가름로 232",
    managed: true,
    hours: { weekday: "10:00-17:00", weekend: "휴무" },
    closedDays: ["토요일", "일요일", "법정공휴일"],
    reservation: true,
    indoor: true,
    facilities: { nursing: true, diaper: true, washingHotWater: true },
    accessibility: { stroller: true, twinStroller: true, elevator: true, ramp: true },
    parking: { available: true, indoor: true, capacity: 90 },
    cost: { free: true },
    ageRange: [0, 36],
    crowdedness: { weekday: "mid", weekend: "n/a" },
    weatherAdapt: { rain: "good", heat: "good", cold: "good", dust: "good" },
    description: "그림책 읽기, 모래놀이 등 영유아 프로그램을 정기 운영합니다.",
    officialUrl: "https://sejong.familynet.or.kr/",
    updatedAt: DATA_UPDATED,
  },
  {
    id: 17,
    name: "보람동 공동육아나눔터",
    category: "공동육아나눔터",
    district: "보람동",
    address: "세종특별자치시 보람북로 28",
    managed: true,
    hours: { weekday: "10:00-17:00", weekend: "휴무" },
    closedDays: ["토요일", "일요일", "법정공휴일"],
    reservation: true,
    indoor: true,
    facilities: { nursing: true, diaper: true, washingHotWater: true },
    accessibility: { stroller: true, twinStroller: true, elevator: true, ramp: true },
    parking: { available: true, indoor: true, capacity: 70 },
    cost: { free: true },
    ageRange: [0, 36],
    crowdedness: { weekday: "mid", weekend: "n/a" },
    weatherAdapt: { rain: "good", heat: "good", cold: "good", dust: "good" },
    description: "보람동 인근 영유아 가정 이용이 많습니다.",
    officialUrl: "https://sejong.familynet.or.kr/",
    updatedAt: DATA_UPDATED,
  },
  {
    id: 18,
    name: "반곡동 공동육아나눔터",
    category: "공동육아나눔터",
    district: "반곡동",
    address: "세종특별자치시 반곡중앙로 89",
    managed: true,
    hours: { weekday: "10:00-17:00", weekend: "휴무" },
    closedDays: ["토요일", "일요일", "법정공휴일"],
    reservation: true,
    indoor: true,
    facilities: { nursing: true, diaper: true, washingHotWater: true },
    accessibility: { stroller: true, twinStroller: true, elevator: true, ramp: true },
    parking: { available: true, indoor: true, capacity: 80 },
    cost: { free: true },
    ageRange: [0, 36],
    crowdedness: { weekday: "mid", weekend: "n/a" },
    weatherAdapt: { rain: "good", heat: "good", cold: "good", dust: "good" },
    description: "최근 개관, 영아 전용 공간이 마련되어 있습니다.",
    officialUrl: "https://sejong.familynet.or.kr/",
    updatedAt: DATA_UPDATED,
  },

  // --- 가족센터 ---
  {
    id: 19,
    name: "세종시 가족센터 (본관)",
    category: "가족센터",
    district: "한솔동",
    address: "세종특별자치시 한누리대로 411",
    managed: true,
    hours: { weekday: "09:00-18:00", weekend: "09:00-13:00" },
    closedDays: ["일요일", "법정공휴일"],
    reservation: true,
    indoor: true,
    facilities: { nursing: true, diaper: true, washingHotWater: true },
    accessibility: { stroller: true, twinStroller: true, elevator: true, ramp: true },
    parking: { available: true, indoor: false, capacity: 40 },
    cost: { free: true },
    ageRange: [0, 36],
    crowdedness: { weekday: "mid", weekend: "low" },
    weatherAdapt: { rain: "good", heat: "good", cold: "good", dust: "good" },
    description: "부모교육, 다문화·한부모 지원, 시간제 돌봄 등 가족 단위 프로그램을 운영합니다.",
    officialUrl: "https://sejong.familynet.or.kr/",
    updatedAt: DATA_UPDATED,
  },
  {
    id: 20,
    name: "세종시 육아종합지원센터",
    category: "가족센터",
    district: "도담동",
    address: "세종특별자치시 도움5로 11",
    managed: true,
    hours: { weekday: "09:00-18:00", weekend: "휴무" },
    closedDays: ["토요일", "일요일", "법정공휴일"],
    reservation: true,
    indoor: true,
    facilities: { nursing: true, diaper: true, washingHotWater: true },
    accessibility: { stroller: true, twinStroller: true, elevator: true, ramp: true },
    parking: { available: true, indoor: true, capacity: 60 },
    cost: { free: true },
    ageRange: [0, 36],
    crowdedness: { weekday: "mid", weekend: "n/a" },
    weatherAdapt: { rain: "good", heat: "good", cold: "good", dust: "good" },
    description: "시간제보육·장난감 대여·부모교육 등 영유아 가정 지원의 핵심 기관입니다.",
    officialUrl: "https://sejong.childcare.go.kr/",
    updatedAt: DATA_UPDATED,
  },

  // --- 박물관/체험관 ---
  {
    id: 21,
    name: "국립어린이박물관",
    category: "박물관·체험관",
    district: "나성동",
    address: "세종특별자치시 다솜로 216",
    managed: false,
    hours: { weekday: "10:00-17:50", weekend: "10:00-17:50" },
    closedDays: ["매주 월요일", "1월 1일", "설·추석 당일"],
    reservation: true,
    indoor: true,
    facilities: { nursing: true, diaper: true, washingHotWater: true },
    accessibility: { stroller: true, twinStroller: true, elevator: true, ramp: true },
    parking: { available: true, indoor: true, capacity: 300 },
    cost: { free: true },
    ageRange: [12, 36],
    crowdedness: { weekday: "mid", weekend: "high" },
    weatherAdapt: { rain: "good", heat: "good", cold: "good", dust: "good" },
    description: "국립 시설이며 세종시 직접 관리 대상은 아닙니다. 사전 예약 필수, 공식 페이지로 안내합니다.",
    officialUrl: "https://www.children.go.kr/",
    updatedAt: DATA_UPDATED,
  },
  {
    id: 22,
    name: "대통령기록관 어린이체험관",
    category: "박물관·체험관",
    district: "어진동",
    address: "세종특별자치시 다솜로 250",
    managed: false,
    hours: { weekday: "09:00-18:00", weekend: "09:00-18:00" },
    closedDays: ["매주 월요일", "1월 1일", "설·추석 당일"],
    reservation: true,
    indoor: true,
    facilities: { nursing: true, diaper: true, washingHotWater: false },
    accessibility: { stroller: true, twinStroller: true, elevator: true, ramp: true },
    parking: { available: true, indoor: true, capacity: 150 },
    cost: { free: true },
    ageRange: [18, 36],
    crowdedness: { weekday: "low", weekend: "mid" },
    weatherAdapt: { rain: "good", heat: "good", cold: "good", dust: "good" },
    description: "국가기록원 운영 시설입니다. 공식 페이지에서 운영시간·예약을 최종 확인하세요.",
    officialUrl: "https://www.pa.go.kr/",
    updatedAt: DATA_UPDATED,
  },

  // --- 공원/수목원 ---
  {
    id: 23,
    name: "세종호수공원",
    category: "공원·야외",
    district: "어진동",
    address: "세종특별자치시 연기면 세종리",
    managed: true,
    hours: { weekday: "상시", weekend: "상시" },
    closedDays: [],
    reservation: false,
    indoor: false,
    facilities: { nursing: false, diaper: true, washingHotWater: false },
    accessibility: { stroller: true, twinStroller: true, elevator: false, ramp: true },
    parking: { available: true, indoor: false, capacity: 500 },
    cost: { free: true },
    ageRange: [6, 36],
    crowdedness: { weekday: "low", weekend: "high" },
    weatherAdapt: { rain: "poor", heat: "poor", cold: "fair", dust: "poor" },
    description: "산책로가 평탄해 유모차 이동이 편합니다. 우천·폭염·미세먼지 나쁨 시 비추천.",
    officialUrl: "https://www.sejong.go.kr/",
    updatedAt: DATA_UPDATED,
  },
  {
    id: 24,
    name: "중앙공원",
    category: "공원·야외",
    district: "어진동",
    address: "세종특별자치시 연기면 세종리",
    managed: true,
    hours: { weekday: "상시", weekend: "상시" },
    closedDays: [],
    reservation: false,
    indoor: false,
    facilities: { nursing: false, diaper: true, washingHotWater: false },
    accessibility: { stroller: true, twinStroller: true, elevator: false, ramp: true },
    parking: { available: true, indoor: false, capacity: 400 },
    cost: { free: true },
    ageRange: [12, 36],
    crowdedness: { weekday: "low", weekend: "high" },
    weatherAdapt: { rain: "poor", heat: "poor", cold: "fair", dust: "poor" },
    description: "넓은 잔디밭과 산책로. 그늘이 부족해 한낮 폭염 시 비추천.",
    officialUrl: "https://www.sejong.go.kr/",
    updatedAt: DATA_UPDATED,
  },
  {
    id: 25,
    name: "국립세종수목원",
    category: "공원·야외",
    district: "어진동",
    address: "세종특별자치시 수목원로 136",
    managed: false,
    hours: { weekday: "09:00-18:00", weekend: "09:00-18:00" },
    closedDays: ["매주 월요일"],
    reservation: false,
    indoor: false,
    facilities: { nursing: true, diaper: true, washingHotWater: true },
    accessibility: { stroller: true, twinStroller: true, elevator: true, ramp: true },
    parking: { available: true, indoor: false, capacity: 300 },
    cost: { free: false, fee: "성인 5,000원, 영유아 무료" },
    ageRange: [12, 36],
    crowdedness: { weekday: "mid", weekend: "high" },
    weatherAdapt: { rain: "fair", heat: "fair", cold: "fair", dust: "fair" },
    description: "온실(실내)이 있어 우천·폭염 시에도 일부 관람 가능. 국립 시설로 공식 안내 링크 제공.",
    officialUrl: "https://www.sjna.or.kr/",
    updatedAt: DATA_UPDATED,
  },

  // --- 보건소 ---
  {
    id: 26,
    name: "세종시 보건소 (모자보건실)",
    category: "보건소",
    district: "보람동",
    address: "세종특별자치시 보듬3로 105",
    managed: true,
    hours: { weekday: "09:00-18:00", weekend: "휴무" },
    closedDays: ["토요일", "일요일", "법정공휴일"],
    reservation: true,
    indoor: true,
    facilities: { nursing: true, diaper: true, washingHotWater: true },
    accessibility: { stroller: true, twinStroller: true, elevator: true, ramp: true },
    parking: { available: true, indoor: false, capacity: 100 },
    cost: { free: true },
    ageRange: [0, 36],
    crowdedness: { weekday: "mid", weekend: "n/a" },
    weatherAdapt: { rain: "good", heat: "good", cold: "good", dust: "good" },
    description: "영유아검진·예방접종 등 모자보건 서비스를 제공합니다.",
    officialUrl: "https://www.sejong.go.kr/health.do",
    updatedAt: DATA_UPDATED,
  },

  // --- 추가 복합커뮤니티/공동육아 ---
  {
    id: 27,
    name: "아름동 공동육아나눔터",
    category: "공동육아나눔터",
    district: "아름동",
    address: "세종특별자치시 아름서길 27",
    managed: true,
    hours: { weekday: "10:00-17:00", weekend: "휴무" },
    closedDays: ["토요일", "일요일", "법정공휴일"],
    reservation: true,
    indoor: true,
    facilities: { nursing: true, diaper: true, washingHotWater: true },
    accessibility: { stroller: true, twinStroller: true, elevator: true, ramp: true },
    parking: { available: true, indoor: true, capacity: 70 },
    cost: { free: true },
    ageRange: [0, 36],
    crowdedness: { weekday: "mid", weekend: "n/a" },
    weatherAdapt: { rain: "good", heat: "good", cold: "good", dust: "good" },
    description: "0~24개월 영아 보호자 모임이 활발합니다.",
    officialUrl: "https://sejong.familynet.or.kr/",
    updatedAt: DATA_UPDATED,
  },
  {
    id: 28,
    name: "종촌동 시립도서관 영유아실",
    category: "도서관",
    district: "종촌동",
    address: "세종특별자치시 절재로 154",
    managed: true,
    hours: { weekday: "09:00-22:00", weekend: "09:00-17:00" },
    closedDays: ["매주 월요일", "1월 1일", "설·추석 당일"],
    reservation: false,
    indoor: true,
    facilities: { nursing: true, diaper: true, washingHotWater: false },
    accessibility: { stroller: true, twinStroller: true, elevator: true, ramp: true },
    parking: { available: true, indoor: true, capacity: 60 },
    cost: { free: true },
    ageRange: [0, 36],
    crowdedness: { weekday: "low", weekend: "mid" },
    weatherAdapt: { rain: "good", heat: "good", cold: "good", dust: "good" },
    description: "장난감도서관 인접, 영유아 보호자 이용 비중이 높습니다.",
    officialUrl: "https://www.sejong.go.kr/lib.do",
    updatedAt: DATA_UPDATED,
  },
  {
    id: 29,
    name: "다정동 공동육아나눔터",
    category: "공동육아나눔터",
    district: "다정동",
    address: "세종특별자치시 다정북로 67",
    managed: true,
    hours: { weekday: "10:00-17:00", weekend: "휴무" },
    closedDays: ["토요일", "일요일", "법정공휴일"],
    reservation: true,
    indoor: true,
    facilities: { nursing: true, diaper: true, washingHotWater: true },
    accessibility: { stroller: true, twinStroller: true, elevator: true, ramp: true },
    parking: { available: true, indoor: true, capacity: 65 },
    cost: { free: true },
    ageRange: [0, 36],
    crowdedness: { weekday: "mid", weekend: "n/a" },
    weatherAdapt: { rain: "good", heat: "good", cold: "good", dust: "good" },
    description: "주중 오전 영아 보호자 프로그램 운영.",
    officialUrl: "https://sejong.familynet.or.kr/",
    updatedAt: DATA_UPDATED,
  },
  {
    id: 30,
    name: "장난감도서관 (육아종합지원센터 내)",
    category: "도서관",
    district: "도담동",
    address: "세종특별자치시 도움5로 11",
    managed: true,
    hours: { weekday: "10:00-17:00", weekend: "휴무" },
    closedDays: ["토요일", "일요일", "법정공휴일"],
    reservation: true,
    indoor: true,
    facilities: { nursing: true, diaper: true, washingHotWater: true },
    accessibility: { stroller: true, twinStroller: true, elevator: true, ramp: true },
    parking: { available: true, indoor: true, capacity: 60 },
    cost: { free: true },
    ageRange: [0, 36],
    crowdedness: { weekday: "mid", weekend: "n/a" },
    weatherAdapt: { rain: "good", heat: "good", cold: "good", dust: "good" },
    description: "장난감 대여 가능. 회원가입 후 이용.",
    officialUrl: "https://sejong.childcare.go.kr/",
    updatedAt: DATA_UPDATED,
  },
];

// 공식정보 라우팅 매핑 (Q&A 기능에서 사용)
const OFFICIAL_LINKS = {
  보육: [
    { name: "세종시 육아종합지원센터", url: "https://sejong.childcare.go.kr/", note: "시간제보육·장난감 대여·부모교육" },
    { name: "임신육아종합포털 아이사랑", url: "https://www.childcare.go.kr/", note: "어린이집 입소 대기, 보육료 안내" },
  ],
  건강: [
    { name: "세종시 보건소", url: "https://www.sejong.go.kr/health.do", note: "영유아검진, 모자보건 상담" },
    { name: "예방접종도우미", url: "https://nip.kdca.go.kr/", note: "표준 예방접종 일정·기록 관리" },
  ],
  예방접종: [
    { name: "예방접종도우미", url: "https://nip.kdca.go.kr/", note: "표준 예방접종 일정·기록 관리" },
    { name: "세종시 보건소", url: "https://www.sejong.go.kr/health.do", note: "보건소 무료 예방접종 안내" },
  ],
  발달: [
    { name: "세종시 보건소 (영유아검진)", url: "https://www.sejong.go.kr/health.do", note: "발달 관련 1차 상담" },
    { name: "국가건강정보포털", url: "https://health.kdca.go.kr/", note: "월령별 발달 정보" },
  ],
  외출: [
    { name: "세종엔", url: "https://www.sejong.go.kr/", note: "세종시 시설·생활정보" },
    { name: "세종시 가족센터", url: "https://sejong.familynet.or.kr/", note: "공동육아나눔터 안내" },
  ],
  프로그램: [
    { name: "세종시 가족센터", url: "https://sejong.familynet.or.kr/", note: "부모교육·가족 프로그램" },
    { name: "세종시 육아종합지원센터", url: "https://sejong.childcare.go.kr/", note: "영유아 프로그램" },
  ],
  응급: [
    { name: "119 (소방·구급)", url: "tel:119", note: "응급 시 즉시 신고" },
    { name: "응급의료포털 E-Gen", url: "https://www.e-gen.or.kr/", note: "가까운 응급실 찾기" },
    { name: "1339 (질병관리청 콜센터)", url: "tel:1339", note: "감염병·건강 상담" },
  ],
};

// 응급/위험신호 체크리스트
const EMERGENCY_CHECKLIST = {
  열: [
    "3개월 미만 영아가 38℃ 이상의 열이 있는 경우",
    "열성 경련을 했거나 의식이 처지는 경우",
    "호흡이 매우 가쁘거나 입술이 파래지는 경우",
    "수분을 거의 섭취하지 못하는 경우",
    "열이 5일 이상 지속되는 경우",
  ],
  호흡: [
    "숨이 가쁘고 갈비뼈가 들어갈 정도로 힘들게 숨을 쉬는 경우",
    "입술·손톱이 파랗게 변하는 경우",
    "쌕쌕거리는 소리가 심하고 점점 악화되는 경우",
  ],
  설사구토: [
    "수분을 전혀 섭취하지 못하는 경우",
    "소변량이 현저히 줄어든 경우 (반나절 이상 기저귀가 마른 경우)",
    "혈변·혈성 구토가 있는 경우",
    "축 처지고 반응이 둔한 경우",
  ],
  발진: [
    "발진과 함께 고열이 동반된 경우",
    "보랏빛 점상출혈이 있는 경우",
    "호흡곤란·얼굴 부종이 동반된 경우",
  ],
};
