/**
 * 아이랑 세종 AI - 시범 데이터
 *
 * 본 데이터는 시연용 모의 데이터입니다.
 * 실제 운영 시에는 담당부서 확인 후 월 1회 갱신하며, 공식 페이지로 최종 안내합니다.
 */

const DATA_UPDATED = "2026-05-15";

// 생활권 목록 (1단계 시범 대상)
const DISTRICTS = [
  "도담동", "아름동", "종촌동", "고운동", "새롬동",
  "다정동", "보람동", "소담동", "반곡동", "한솔동",
  "어진동", "나성동", "대평동"
];

// 시설 데이터
// managed: 세종시 직접 관리 여부 (true=표준 정보표 관리, false=공식 링크 안내)
const FACILITIES = [
  {
    id: 1,
    name: "도담동 복합커뮤니티센터",
    category: "복합커뮤니티센터",
    district: "도담동",
    address: "세종특별자치시 도움5로 11",
    managed: true,
    hours: { weekday: "09:00-22:00", weekend: "09:00-18:00", note: "주민자치 공간은 별도 운영" },
    closedDays: ["1월 1일", "설·추석 당일"],
    reservation: false,
    indoor: true,
    facilities: { nursing: true, diaper: true, washingHotWater: true },
    accessibility: { stroller: true, twinStroller: true, elevator: true, ramp: true },
    parking: { available: true, indoor: true, capacity: 80 },
    cost: { free: true },
    ageRange: [0, 36],
    crowdedness: { weekday: "low", weekend: "mid" },
    weatherAdapt: { rain: "good", heat: "good", cold: "good", dust: "good" },
    description: "도서관·체육·문화시설이 한 건물에 있어 영유아 동반 외출에 적합합니다.",
    officialUrl: "https://www.sejong.go.kr/",
    updatedAt: DATA_UPDATED,
  },
  {
    id: 2,
    name: "아름동 복합커뮤니티센터",
    category: "복합커뮤니티센터",
    district: "아름동",
    address: "세종특별자치시 아름서길 27",
    managed: true,
    hours: { weekday: "09:00-22:00", weekend: "09:00-18:00" },
    closedDays: ["1월 1일", "설·추석 당일"],
    reservation: false,
    indoor: true,
    facilities: { nursing: true, diaper: true, washingHotWater: true },
    accessibility: { stroller: true, twinStroller: true, elevator: true, ramp: true },
    parking: { available: true, indoor: true, capacity: 70 },
    cost: { free: true },
    ageRange: [0, 36],
    crowdedness: { weekday: "low", weekend: "high" },
    weatherAdapt: { rain: "good", heat: "good", cold: "good", dust: "good" },
    description: "어린이도서관과 다목적실이 함께 있어 우천·폭염 시 머물기 좋습니다.",
    officialUrl: "https://www.sejong.go.kr/",
    updatedAt: DATA_UPDATED,
  },
  {
    id: 3,
    name: "종촌동 복합커뮤니티센터",
    category: "복합커뮤니티센터",
    district: "종촌동",
    address: "세종특별자치시 절재로 154",
    managed: true,
    hours: { weekday: "09:00-22:00", weekend: "09:00-18:00" },
    closedDays: ["1월 1일", "설·추석 당일"],
    reservation: false,
    indoor: true,
    facilities: { nursing: true, diaper: true, washingHotWater: false },
    accessibility: { stroller: true, twinStroller: true, elevator: true, ramp: true },
    parking: { available: true, indoor: true, capacity: 60 },
    cost: { free: true },
    ageRange: [0, 36],
    crowdedness: { weekday: "low", weekend: "mid" },
    weatherAdapt: { rain: "good", heat: "good", cold: "good", dust: "good" },
    description: "장난감도서관이 인접해 영유아 가정 이용이 많습니다.",
    officialUrl: "https://www.sejong.go.kr/",
    updatedAt: DATA_UPDATED,
  },
  {
    id: 4,
    name: "고운동 복합커뮤니티센터",
    category: "복합커뮤니티센터",
    district: "고운동",
    address: "세종특별자치시 가름로 232",
    managed: true,
    hours: { weekday: "09:00-22:00", weekend: "09:00-18:00" },
    closedDays: ["1월 1일", "설·추석 당일"],
    reservation: false,
    indoor: true,
    facilities: { nursing: true, diaper: true, washingHotWater: true },
    accessibility: { stroller: true, twinStroller: true, elevator: true, ramp: true },
    parking: { available: true, indoor: true, capacity: 90 },
    cost: { free: true },
    ageRange: [0, 36],
    crowdedness: { weekday: "low", weekend: "high" },
    weatherAdapt: { rain: "good", heat: "good", cold: "good", dust: "good" },
    description: "넓은 광장과 실내 공간이 모두 있어 날씨와 무관하게 이용 가능합니다.",
    officialUrl: "https://www.sejong.go.kr/",
    updatedAt: DATA_UPDATED,
  },
  {
    id: 5,
    name: "새롬동 복합커뮤니티센터",
    category: "복합커뮤니티센터",
    district: "새롬동",
    address: "세종특별자치시 새롬중앙로 84",
    managed: true,
    hours: { weekday: "09:00-22:00", weekend: "09:00-18:00" },
    closedDays: ["1월 1일", "설·추석 당일"],
    reservation: false,
    indoor: true,
    facilities: { nursing: true, diaper: true, washingHotWater: true },
    accessibility: { stroller: true, twinStroller: true, elevator: true, ramp: true },
    parking: { available: true, indoor: true, capacity: 75 },
    cost: { free: true },
    ageRange: [0, 36],
    crowdedness: { weekday: "low", weekend: "mid" },
    weatherAdapt: { rain: "good", heat: "good", cold: "good", dust: "good" },
    description: "공동육아나눔터와 함께 이용 가능합니다.",
    officialUrl: "https://www.sejong.go.kr/",
    updatedAt: DATA_UPDATED,
  },
  {
    id: 6,
    name: "다정동 복합커뮤니티센터",
    category: "복합커뮤니티센터",
    district: "다정동",
    address: "세종특별자치시 다정북로 67",
    managed: true,
    hours: { weekday: "09:00-22:00", weekend: "09:00-18:00" },
    closedDays: ["1월 1일", "설·추석 당일"],
    reservation: false,
    indoor: true,
    facilities: { nursing: true, diaper: true, washingHotWater: false },
    accessibility: { stroller: true, twinStroller: true, elevator: true, ramp: true },
    parking: { available: true, indoor: true, capacity: 65 },
    cost: { free: true },
    ageRange: [0, 36],
    crowdedness: { weekday: "low", weekend: "mid" },
    weatherAdapt: { rain: "good", heat: "good", cold: "good", dust: "good" },
    description: "최근 개관한 시설로 영유아 편의시설 상태가 양호합니다.",
    officialUrl: "https://www.sejong.go.kr/",
    updatedAt: DATA_UPDATED,
  },
  {
    id: 7,
    name: "보람동 복합커뮤니티센터",
    category: "복합커뮤니티센터",
    district: "보람동",
    address: "세종특별자치시 보람북로 28",
    managed: true,
    hours: { weekday: "09:00-22:00", weekend: "09:00-18:00" },
    closedDays: ["1월 1일", "설·추석 당일"],
    reservation: false,
    indoor: true,
    facilities: { nursing: true, diaper: true, washingHotWater: true },
    accessibility: { stroller: true, twinStroller: true, elevator: true, ramp: true },
    parking: { available: true, indoor: true, capacity: 70 },
    cost: { free: true },
    ageRange: [0, 36],
    crowdedness: { weekday: "low", weekend: "mid" },
    weatherAdapt: { rain: "good", heat: "good", cold: "good", dust: "good" },
    description: "어진동·보람동 생활권 가족 이용이 많습니다.",
    officialUrl: "https://www.sejong.go.kr/",
    updatedAt: DATA_UPDATED,
  },
  {
    id: 8,
    name: "소담동 복합커뮤니티센터",
    category: "복합커뮤니티센터",
    district: "소담동",
    address: "세종특별자치시 소담1로 22",
    managed: true,
    hours: { weekday: "09:00-22:00", weekend: "09:00-18:00" },
    closedDays: ["1월 1일", "설·추석 당일"],
    reservation: false,
    indoor: true,
    facilities: { nursing: true, diaper: true, washingHotWater: false },
    accessibility: { stroller: true, twinStroller: true, elevator: true, ramp: true },
    parking: { available: true, indoor: true, capacity: 60 },
    cost: { free: true },
    ageRange: [0, 36],
    crowdedness: { weekday: "low", weekend: "low" },
    weatherAdapt: { rain: "good", heat: "good", cold: "good", dust: "good" },
    description: "비교적 한산하여 영아 동반 외출에 부담이 적습니다.",
    officialUrl: "https://www.sejong.go.kr/",
    updatedAt: DATA_UPDATED,
  },
  {
    id: 9,
    name: "반곡동 복합커뮤니티센터",
    category: "복합커뮤니티센터",
    district: "반곡동",
    address: "세종특별자치시 반곡중앙로 89",
    managed: true,
    hours: { weekday: "09:00-22:00", weekend: "09:00-18:00" },
    closedDays: ["1월 1일", "설·추석 당일"],
    reservation: false,
    indoor: true,
    facilities: { nursing: true, diaper: true, washingHotWater: true },
    accessibility: { stroller: true, twinStroller: true, elevator: true, ramp: true },
    parking: { available: true, indoor: true, capacity: 80 },
    cost: { free: true },
    ageRange: [0, 36],
    crowdedness: { weekday: "low", weekend: "mid" },
    weatherAdapt: { rain: "good", heat: "good", cold: "good", dust: "good" },
    description: "신규 입주지역에 위치하여 영유아 가구 비중이 높습니다.",
    officialUrl: "https://www.sejong.go.kr/",
    updatedAt: DATA_UPDATED,
  },
  {
    id: 10,
    name: "한솔동 복합커뮤니티센터",
    category: "복합커뮤니티센터",
    district: "한솔동",
    address: "세종특별자치시 한누리대로 411",
    managed: true,
    hours: { weekday: "09:00-22:00", weekend: "09:00-18:00" },
    closedDays: ["1월 1일", "설·추석 당일"],
    reservation: false,
    indoor: true,
    facilities: { nursing: true, diaper: true, washingHotWater: false },
    accessibility: { stroller: true, twinStroller: false, elevator: true, ramp: true },
    parking: { available: true, indoor: false, capacity: 40 },
    cost: { free: true },
    ageRange: [0, 36],
    crowdedness: { weekday: "low", weekend: "mid" },
    weatherAdapt: { rain: "good", heat: "good", cold: "good", dust: "good" },
    description: "초기 조성지역으로 출입 동선이 다소 좁아 광폭 유모차는 사전 확인 권장.",
    officialUrl: "https://www.sejong.go.kr/",
    updatedAt: DATA_UPDATED,
  },

  // --- 도서관 ---
  {
    id: 11,
    name: "도담동 시립도서관 영유아실",
    category: "도서관",
    district: "도담동",
    address: "세종특별자치시 도움5로 11",
    managed: true,
    hours: { weekday: "09:00-22:00", weekend: "09:00-17:00" },
    closedDays: ["매주 월요일", "1월 1일", "설·추석 당일"],
    reservation: false,
    indoor: true,
    facilities: { nursing: true, diaper: true, washingHotWater: false },
    accessibility: { stroller: true, twinStroller: true, elevator: true, ramp: true },
    parking: { available: true, indoor: true, capacity: 80 },
    cost: { free: true },
    ageRange: [0, 36],
    crowdedness: { weekday: "low", weekend: "high" },
    weatherAdapt: { rain: "good", heat: "good", cold: "good", dust: "good" },
    description: "영유아 전용 공간과 그림책 구역이 분리되어 있어 조용히 머물기 좋습니다.",
    officialUrl: "https://www.sejong.go.kr/lib.do",
    updatedAt: DATA_UPDATED,
  },
  {
    id: 12,
    name: "새롬동 시립도서관 영유아실",
    category: "도서관",
    district: "새롬동",
    address: "세종특별자치시 새롬중앙로 84",
    managed: true,
    hours: { weekday: "09:00-22:00", weekend: "09:00-17:00" },
    closedDays: ["매주 월요일", "1월 1일", "설·추석 당일"],
    reservation: false,
    indoor: true,
    facilities: { nursing: true, diaper: true, washingHotWater: false },
    accessibility: { stroller: true, twinStroller: true, elevator: true, ramp: true },
    parking: { available: true, indoor: true, capacity: 75 },
    cost: { free: true },
    ageRange: [0, 36],
    crowdedness: { weekday: "low", weekend: "mid" },
    weatherAdapt: { rain: "good", heat: "good", cold: "good", dust: "good" },
    description: "그림책 읽기 프로그램을 정기 운영합니다.",
    officialUrl: "https://www.sejong.go.kr/lib.do",
    updatedAt: DATA_UPDATED,
  },
  {
    id: 13,
    name: "고운동 시립도서관 영유아실",
    category: "도서관",
    district: "고운동",
    address: "세종특별자치시 가름로 232",
    managed: true,
    hours: { weekday: "09:00-22:00", weekend: "09:00-17:00" },
    closedDays: ["매주 월요일", "1월 1일", "설·추석 당일"],
    reservation: false,
    indoor: true,
    facilities: { nursing: true, diaper: true, washingHotWater: false },
    accessibility: { stroller: true, twinStroller: true, elevator: true, ramp: true },
    parking: { available: true, indoor: true, capacity: 90 },
    cost: { free: true },
    ageRange: [0, 36],
    crowdedness: { weekday: "low", weekend: "mid" },
    weatherAdapt: { rain: "good", heat: "good", cold: "good", dust: "good" },
    description: "넓은 영유아 공간과 다양한 그림책 보유.",
    officialUrl: "https://www.sejong.go.kr/lib.do",
    updatedAt: DATA_UPDATED,
  },
  {
    id: 14,
    name: "국립세종도서관 어린이자료실",
    category: "도서관",
    district: "어진동",
    address: "세종특별자치시 다솜3로 48",
    managed: false,
    hours: { weekday: "09:00-18:00", weekend: "09:00-18:00" },
    closedDays: ["매월 둘째·넷째 월요일", "1월 1일", "설·추석 당일"],
    reservation: false,
    indoor: true,
    facilities: { nursing: true, diaper: true, washingHotWater: false },
    accessibility: { stroller: true, twinStroller: true, elevator: true, ramp: true },
    parking: { available: true, indoor: true, capacity: 200 },
    cost: { free: true },
    ageRange: [6, 36],
    crowdedness: { weekday: "mid", weekend: "high" },
    weatherAdapt: { rain: "good", heat: "good", cold: "good", dust: "good" },
    description: "국립도서관 직영 시설입니다. 세종시 직접 관리 대상은 아니며 공식 페이지로 안내합니다.",
    officialUrl: "https://sejong.nl.go.kr/",
    updatedAt: DATA_UPDATED,
  },

  // --- 공동육아나눔터 ---
  {
    id: 15,
    name: "도담동 공동육아나눔터",
    category: "공동육아나눔터",
    district: "도담동",
    address: "세종특별자치시 도움5로 11",
    managed: true,
    hours: { weekday: "10:00-17:00", weekend: "휴무" },
    closedDays: ["토요일", "일요일", "법정공휴일"],
    reservation: true,
    indoor: true,
    facilities: { nursing: true, diaper: true, washingHotWater: true },
    accessibility: { stroller: true, twinStroller: true, elevator: true, ramp: true },
    parking: { available: true, indoor: true, capacity: 80 },
    cost: { free: true },
    ageRange: [0, 36],
    crowdedness: { weekday: "mid", weekend: "n/a" },
    weatherAdapt: { rain: "good", heat: "good", cold: "good", dust: "good" },
    description: "예약제로 운영되며 영유아 보호자 교류 프로그램을 함께 운영합니다.",
    officialUrl: "https://sejong.familynet.or.kr/",
    updatedAt: DATA_UPDATED,
  },
  {
    id: 16,
    name: "고운동 공동육아나눔터",
    category: "공동육아나눔터",
    district: "고운동",
    address: "세종특별자치시 가름로 232",
    managed: true,
    hours: { weekday: "10:00-17:00", weekend: "휴무" },
    closedDays: ["토요일", "일요일", "법정공휴일"],
    reservation: true,
    indoor: true,
    facilities: { nursing: true, diaper: true, washingHotWater: true },
    accessibility: { stroller: true, twinStroller: true, elevator: true, ramp: true },
    parking: { available: true, indoor: true, capacity: 90 },
    cost: { free: true },
    ageRange: [0, 36],
    crowdedness: { weekday: "mid", weekend: "n/a" },
    weatherAdapt: { rain: "good", heat: "good", cold: "good", dust: "good" },
    description: "그림책 읽기, 모래놀이 등 영유아 프로그램을 정기 운영합니다.",
    officialUrl: "https://sejong.familynet.or.kr/",
    updatedAt: DATA_UPDATED,
  },
  {
    id: 17,
    name: "보람동 공동육아나눔터",
    category: "공동육아나눔터",
    district: "보람동",
    address: "세종특별자치시 보람북로 28",
    managed: true,
    hours: { weekday: "10:00-17:00", weekend: "휴무" },
    closedDays: ["토요일", "일요일", "법정공휴일"],
    reservation: true,
    indoor: true,
    facilities: { nursing: true, diaper: true, washingHotWater: true },
    accessibility: { stroller: true, twinStroller: true, elevator: true, ramp: true },
    parking: { available: true, indoor: true, capacity: 70 },
    cost: { free: true },
    ageRange: [0, 36],
    crowdedness: { weekday: "mid", weekend: "n/a" },
    weatherAdapt: { rain: "good", heat: "good", cold: "good", dust: "good" },
    description: "보람동 인근 영유아 가정 이용이 많습니다.",
    officialUrl: "https://sejong.familynet.or.kr/",
    updatedAt: DATA_UPDATED,
  },
  {
    id: 18,
    name: "반곡동 공동육아나눔터",
    category: "공동육아나눔터",
    district: "반곡동",
    address: "세종특별자치시 반곡중앙로 89",
    managed: true,
    hours: { weekday: "10:00-17:00", weekend: "휴무" },
    closedDays: ["토요일", "일요일", "법정공휴일"],
    reservation: true,
    indoor: true,
    facilities: { nursing: true, diaper: true, washingHotWater: true },
    accessibility: { stroller: true, twinStroller: true, elevator: true, ramp: true },
    parking: { available: true, indoor: true, capacity: 80 },
    cost: { free: true },
    ageRange: [0, 36],
    crowdedness: { weekday: "mid", weekend: "n/a" },
    weatherAdapt: { rain: "good", heat: "good", cold: "good", dust: "good" },
    description: "최근 개관, 영아 전용 공간이 마련되어 있습니다.",
    officialUrl: "https://sejong.familynet.or.kr/",
    updatedAt: DATA_UPDATED,
  },

  // --- 가족센터 ---
  {
    id: 19,
    name: "세종시 가족센터 (본관)",
    category: "가족센터",
    district: "한솔동",
    address: "세종특별자치시 한누리대로 411",
    managed: true,
    hours: { weekday: "09:00-18:00", weekend: "09:00-13:00" },
    closedDays: ["일요일", "법정공휴일"],
    reservation: true,
    indoor: true,
    facilities: { nursing: true, diaper: true, washingHotWater: true },
    accessibility: { stroller: true, twinStroller: true, elevator: true, ramp: true },
    parking: { available: true, indoor: false, capacity: 40 },
    cost: { free: true },
    ageRange: [0, 36],
    crowdedness: { weekday: "mid", weekend: "low" },
    weatherAdapt: { rain: "good", heat: "good", cold: "good", dust: "good" },
    description: "부모교육, 다문화·한부모 지원, 시간제 돌봄 등 가족 단위 프로그램을 운영합니다.",
    officialUrl: "https://sejong.familynet.or.kr/",
    updatedAt: DATA_UPDATED,
  },
  {
    id: 20,
    name: "세종시 육아종합지원센터",
    category: "가족센터",
    district: "도담동",
    address: "세종특별자치시 도움5로 11",
    managed: true,
    hours: { weekday: "09:00-18:00", weekend: "휴무" },
    closedDays: ["토요일", "일요일", "법정공휴일"],
    reservation: true,
    indoor: true,
    facilities: { nursing: true, diaper: true, washingHotWater: true },
    accessibility: { stroller: true, twinStroller: true, elevator: true, ramp: true },
    parking: { available: true, indoor: true, capacity: 60 },
    cost: { free: true },
    ageRange: [0, 36],
    crowdedness: { weekday: "mid", weekend: "n/a" },
    weatherAdapt: { rain: "good", heat: "good", cold: "good", dust: "good" },
    description: "시간제보육·장난감 대여·부모교육 등 영유아 가정 지원의 핵심 기관입니다.",
    officialUrl: "https://sejong.childcare.go.kr/",
    updatedAt: DATA_UPDATED,
  },

  // --- 박물관/체험관 ---
  {
    id: 21,
    name: "국립어린이박물관",
    category: "박물관·체험관",
    district: "나성동",
    address: "세종특별자치시 다솜로 216",
    managed: false,
    hours: { weekday: "10:00-17:50", weekend: "10:00-17:50" },
    closedDays: ["매주 월요일", "1월 1일", "설·추석 당일"],
    reservation: true,
    indoor: true,
    facilities: { nursing: true, diaper: true, washingHotWater: true },
    accessibility: { stroller: true, twinStroller: true, elevator: true, ramp: true },
    parking: { available: true, indoor: true, capacity: 300 },
    cost: { free: true },
    ageRange: [12, 36],
    crowdedness: { weekday: "mid", weekend: "high" },
    weatherAdapt: { rain: "good", heat: "good", cold: "good", dust: "good" },
    description: "국립 시설이며 세종시 직접 관리 대상은 아닙니다. 사전 예약 필수, 공식 페이지로 안내합니다.",
    officialUrl: "https://www.children.go.kr/",
    updatedAt: DATA_UPDATED,
  },
  {
    id: 22,
    name: "대통령기록관 어린이체험관",
    category: "박물관·체험관",
    district: "어진동",
    address: "세종특별자치시 다솜로 250",
    managed: false,
    hours: { weekday: "09:00-18:00", weekend: "09:00-18:00" },
    closedDays: ["매주 월요일", "1월 1일", "설·추석 당일"],
    reservation: true,
    indoor: true,
    facilities: { nursing: true, diaper: true, washingHotWater: false },
    accessibility: { stroller: true, twinStroller: true, elevator: true, ramp: true },
    parking: { available: true, indoor: true, capacity: 150 },
    cost: { free: true },
    ageRange: [18, 36],
    crowdedness: { weekday: "low", weekend: "mid" },
    weatherAdapt: { rain: "good", heat: "good", cold: "good", dust: "good" },
    description: "국가기록원 운영 시설입니다. 공식 페이지에서 운영시간·예약을 최종 확인하세요.",
    officialUrl: "https://www.pa.go.kr/",
    updatedAt: DATA_UPDATED,
  },

  // --- 공원/수목원 ---
  {
    id: 23,
    name: "세종호수공원",
    category: "공원·야외",
    district: "어진동",
    address: "세종특별자치시 연기면 세종리",
    managed: true,
    hours: { weekday: "상시", weekend: "상시" },
    closedDays: [],
    reservation: false,
    indoor: false,
    facilities: { nursing: false, diaper: true, washingHotWater: false },
    accessibility: { stroller: true, twinStroller: true, elevator: false, ramp: true },
    parking: { available: true, indoor: false, capacity: 500 },
    cost: { free: true },
    ageRange: [6, 36],
    crowdedness: { weekday: "low", weekend: "high" },
    weatherAdapt: { rain: "poor", heat: "poor", cold: "fair", dust: "poor" },
    description: "산책로가 평탄해 유모차 이동이 편합니다. 우천·폭염·미세먼지 나쁨 시 비추천.",
    officialUrl: "https://www.sejong.go.kr/",
    updatedAt: DATA_UPDATED,
  },
  {
    id: 24,
    name: "중앙공원",
    category: "공원·야외",
    district: "어진동",
    address: "세종특별자치시 연기면 세종리",
    managed: true,
    hours: { weekday: "상시", weekend: "상시" },
    closedDays: [],
    reservation: false,
    indoor: false,
    facilities: { nursing: false, diaper: true, washingHotWater: false },
    accessibility: { stroller: true, twinStroller: true, elevator: false, ramp: true },
    parking: { available: true, indoor: false, capacity: 400 },
    cost: { free: true },
    ageRange: [12, 36],
    crowdedness: { weekday: "low", weekend: "high" },
    weatherAdapt: { rain: "poor", heat: "poor", cold: "fair", dust: "poor" },
    description: "넓은 잔디밭과 산책로. 그늘이 부족해 한낮 폭염 시 비추천.",
    officialUrl: "https://www.sejong.go.kr/",
    updatedAt: DATA_UPDATED,
  },
  {
    id: 25,
    name: "국립세종수목원",
    category: "공원·야외",
    district: "어진동",
    address: "세종특별자치시 수목원로 136",
    managed: false,
    hours: { weekday: "09:00-18:00", weekend: "09:00-18:00" },
    closedDays: ["매주 월요일"],
    reservation: false,
    indoor: false,
    facilities: { nursing: true, diaper: true, washingHotWater: true },
    accessibility: { stroller: true, twinStroller: true, elevator: true, ramp: true },
    parking: { available: true, indoor: false, capacity: 300 },
    cost: { free: false, fee: "성인 5,000원, 영유아 무료" },
    ageRange: [12, 36],
    crowdedness: { weekday: "mid", weekend: "high" },
    weatherAdapt: { rain: "fair", heat: "fair", cold: "fair", dust: "fair" },
    description: "온실(실내)이 있어 우천·폭염 시에도 일부 관람 가능. 국립 시설로 공식 안내 링크 제공.",
    officialUrl: "https://www.sjna.or.kr/",
    updatedAt: DATA_UPDATED,
  },

  // --- 보건소 ---
  {
    id: 26,
    name: "세종시 보건소 (모자보건실)",
    category: "보건소",
    district: "보람동",
    address: "세종특별자치시 보듬3로 105",
    managed: true,
    hours: { weekday: "09:00-18:00", weekend: "휴무" },
    closedDays: ["토요일", "일요일", "법정공휴일"],
    reservation: true,
    indoor: true,
    facilities: { nursing: true, diaper: true, washingHotWater: true },
    accessibility: { stroller: true, twinStroller: true, elevator: true, ramp: true },
    parking: { available: true, indoor: false, capacity: 100 },
    cost: { free: true },
    ageRange: [0, 36],
    crowdedness: { weekday: "mid", weekend: "n/a" },
    weatherAdapt: { rain: "good", heat: "good", cold: "good", dust: "good" },
    description: "영유아검진·예방접종 등 모자보건 서비스를 제공합니다.",
    officialUrl: "https://www.sejong.go.kr/health.do",
    updatedAt: DATA_UPDATED,
  },

  // --- 추가 복합커뮤니티/공동육아 ---
  {
    id: 27,
    name: "아름동 공동육아나눔터",
    category: "공동육아나눔터",
    district: "아름동",
    address: "세종특별자치시 아름서길 27",
    managed: true,
    hours: { weekday: "10:00-17:00", weekend: "휴무" },
    closedDays: ["토요일", "일요일", "법정공휴일"],
    reservation: true,
    indoor: true,
    facilities: { nursing: true, diaper: true, washingHotWater: true },
    accessibility: { stroller: true, twinStroller: true, elevator: true, ramp: true },
    parking: { available: true, indoor: true, capacity: 70 },
    cost: { free: true },
    ageRange: [0, 36],
    crowdedness: { weekday: "mid", weekend: "n/a" },
    weatherAdapt: { rain: "good", heat: "good", cold: "good", dust: "good" },
    description: "0~24개월 영아 보호자 모임이 활발합니다.",
    officialUrl: "https://sejong.familynet.or.kr/",
    updatedAt: DATA_UPDATED,
  },
  {
    id: 28,
    name: "종촌동 시립도서관 영유아실",
    category: "도서관",
    district: "종촌동",
    address: "세종특별자치시 절재로 154",
    managed: true,
    hours: { weekday: "09:00-22:00", weekend: "09:00-17:00" },
    closedDays: ["매주 월요일", "1월 1일", "설·추석 당일"],
    reservation: false,
    indoor: true,
    facilities: { nursing: true, diaper: true, washingHotWater: false },
    accessibility: { stroller: true, twinStroller: true, elevator: true, ramp: true },
    parking: { available: true, indoor: true, capacity: 60 },
    cost: { free: true },
    ageRange: [0, 36],
    crowdedness: { weekday: "low", weekend: "mid" },
    weatherAdapt: { rain: "good", heat: "good", cold: "good", dust: "good" },
    description: "장난감도서관 인접, 영유아 보호자 이용 비중이 높습니다.",
    officialUrl: "https://www.sejong.go.kr/lib.do",
    updatedAt: DATA_UPDATED,
  },
  {
    id: 29,
    name: "다정동 공동육아나눔터",
    category: "공동육아나눔터",
    district: "다정동",
    address: "세종특별자치시 다정북로 67",
    managed: true,
    hours: { weekday: "10:00-17:00", weekend: "휴무" },
    closedDays: ["토요일", "일요일", "법정공휴일"],
    reservation: true,
    indoor: true,
    facilities: { nursing: true, diaper: true, washingHotWater: true },
    accessibility: { stroller: true, twinStroller: true, elevator: true, ramp: true },
    parking: { available: true, indoor: true, capacity: 65 },
    cost: { free: true },
    ageRange: [0, 36],
    crowdedness: { weekday: "mid", weekend: "n/a" },
    weatherAdapt: { rain: "good", heat: "good", cold: "good", dust: "good" },
    description: "주중 오전 영아 보호자 프로그램 운영.",
    officialUrl: "https://sejong.familynet.or.kr/",
    updatedAt: DATA_UPDATED,
  },
  {
    id: 30,
    name: "장난감도서관 (육아종합지원센터 내)",
    category: "도서관",
    district: "도담동",
    address: "세종특별자치시 도움5로 11",
    managed: true,
    hours: { weekday: "10:00-17:00", weekend: "휴무" },
    closedDays: ["토요일", "일요일", "법정공휴일"],
    reservation: true,
    indoor: true,
    facilities: { nursing: true, diaper: true, washingHotWater: true },
    accessibility: { stroller: true, twinStroller: true, elevator: true, ramp: true },
    parking: { available: true, indoor: true, capacity: 60 },
    cost: { free: true },
    ageRange: [0, 36],
    crowdedness: { weekday: "mid", weekend: "n/a" },
    weatherAdapt: { rain: "good", heat: "good", cold: "good", dust: "good" },
    description: "장난감 대여 가능. 회원가입 후 이용.",
    officialUrl: "https://sejong.childcare.go.kr/",
    updatedAt: DATA_UPDATED,
  },
];

// 공식정보 라우팅 매핑 (Q&A 기능에서 사용)
const OFFICIAL_LINKS = {
  보육: [
    { name: "세종시 육아종합지원센터", url: "https://sejong.childcare.go.kr/", note: "시간제보육·장난감 대여·부모교육" },
    { name: "임신육아종합포털 아이사랑", url: "https://www.childcare.go.kr/", note: "어린이집 입소 대기, 보육료 안내" },
  ],
  건강: [
    { name: "세종시 보건소", url: "https://www.sejong.go.kr/health.do", note: "영유아검진, 모자보건 상담" },
    { name: "예방접종도우미", url: "https://nip.kdca.go.kr/", note: "표준 예방접종 일정·기록 관리" },
  ],
  예방접종: [
    { name: "예방접종도우미", url: "https://nip.kdca.go.kr/", note: "표준 예방접종 일정·기록 관리" },
    { name: "세종시 보건소", url: "https://www.sejong.go.kr/health.do", note: "보건소 무료 예방접종 안내" },
  ],
  발달: [
    { name: "세종시 보건소 (영유아검진)", url: "https://www.sejong.go.kr/health.do", note: "발달 관련 1차 상담" },
    { name: "국가건강정보포털", url: "https://health.kdca.go.kr/", note: "월령별 발달 정보" },
  ],
  외출: [
    { name: "세종엔", url: "https://www.sejong.go.kr/", note: "세종시 시설·생활정보" },
    { name: "세종시 가족센터", url: "https://sejong.familynet.or.kr/", note: "공동육아나눔터 안내" },
  ],
  프로그램: [
    { name: "세종시 가족센터", url: "https://sejong.familynet.or.kr/", note: "부모교육·가족 프로그램" },
    { name: "세종시 육아종합지원센터", url: "https://sejong.childcare.go.kr/", note: "영유아 프로그램" },
  ],
  응급: [
    { name: "119 (소방·구급)", url: "tel:119", note: "응급 시 즉시 신고" },
    { name: "응급의료포털 E-Gen", url: "https://www.e-gen.or.kr/", note: "가까운 응급실 찾기" },
    { name: "달빛어린이병원·야간휴일 소아진료", url: "https://www.e-gen.or.kr/", note: "야간·휴일 소아진료 가능 기관 검색" },
    { name: "1339 (질병관리청 콜센터)", url: "tel:1339", note: "24시간 감염병·건강 상담" },
  ],
  열: [
    { name: "응급의료포털 E-Gen", url: "https://www.e-gen.or.kr/", note: "야간·휴일 소아진료·응급실 찾기" },
    { name: "세종시 보건소", url: "https://www.sejong.go.kr/health.do", note: "영유아 건강 상담" },
    { name: "1339 (질병관리청 콜센터)", url: "tel:1339", note: "24시간 건강 상담" },
  ],
};

// ============================================================
// AI 질문 분류 메타 (질문 분석 결과 박스 · 처리 단계에서 사용)
// urgency: "high"(응급) | "caution"(주의) | "info"(일반)
// ============================================================
const QA_META = {
  응급: {
    topic: "응급 / 위험징후", urgency: "high", urgencyLabel: "응급 의심",
    principle: "AI는 진단하지 않습니다. 위험신호를 먼저 확인하고, 해당 시 즉시 공식 응급경로로 안내합니다.",
    steps: [
      "위험신호 체크리스트로 응급 여부를 1차 확인",
      "해당하면 119 또는 응급의료포털로 즉시 연결",
      "야간·휴일이면 소아진료 가능 기관 검색 안내",
    ],
  },
  열: {
    topic: "건강 / 발열", urgency: "caution", urgencyLabel: "주의 필요",
    principle: "AI는 진단하지 않습니다. 발열 위험신호를 확인하고 공식 건강정보·기관으로 안내합니다.",
    steps: [
      "발열 관련 위험신호 확인",
      "해당 없으면 가정 내 관찰 요령은 공식 건강정보로 안내",
      "야간·휴일 진료가 필요하면 소아진료 기관 검색 연결",
    ],
  },
  예방접종: {
    topic: "예방접종", urgency: "info", urgencyLabel: "일반 정보",
    principle: "표준 일정·접종 기록은 공식 시스템(예방접종도우미)에서 확인하도록 안내합니다.",
    steps: [
      "월령별 표준 예방접종 일정 안내",
      "누락·지연 접종 확인 방법 안내",
      "보건소 무료 예방접종 대상 여부 확인 연결",
    ],
  },
  발달: {
    topic: "발달 / 성장", urgency: "caution", urgencyLabel: "상담 권장",
    principle: "AI는 발달을 진단하지 않습니다. 월령별 일반 정보와 공식 발달상담 경로로 안내합니다.",
    steps: [
      "월령별 발달 이정표(일반 정보) 안내",
      "영유아 건강검진의 발달평가 항목 안내",
      "우려가 지속되면 보건소·전문기관 상담 경로 연결",
    ],
  },
  보육: {
    topic: "보육 / 시간제보육", urgency: "info", urgencyLabel: "일반 정보",
    principle: "신청 가능 여부와 정원은 공식 페이지에서 최종 확인하도록 안내합니다.",
    steps: [
      "시간제보육 제도 및 이용 대상 안내",
      "생활권 내 제공기관 확인 방법 안내",
      "신청 방법·준비물 안내",
      "공식 신청 페이지(아이사랑)로 연결",
    ],
  },
  외출: {
    topic: "외출 / 나들이", urgency: "info", urgencyLabel: "일반 정보",
    principle: "오늘 날씨·월령·이동 조건을 반영한 장소 추천은 '외출 추천' 기능으로 연결합니다.",
    steps: [
      "질문에서 월령·날씨·이동 조건 파악",
      "외출 추천 기능으로 오늘 이용 가능한 공공자원 추천",
      "수유실·기저귀대·유모차 접근성 등 확인 정보 제공",
    ],
  },
  프로그램: {
    topic: "프로그램 / 교육", urgency: "info", urgencyLabel: "일반 정보",
    principle: "운영 일정·모집은 공식 페이지에서 확인하도록 안내합니다.",
    steps: [
      "가족센터·육아종합지원센터 영유아 프로그램 안내",
      "공동육아나눔터 또래모임 안내",
      "신청·모집 일정 공식 페이지 연결",
    ],
  },
  건강: {
    topic: "건강 / 증상", urgency: "caution", urgencyLabel: "주의 필요",
    principle: "AI는 진단하지 않습니다. 위험신호 확인 후 공식 건강정보·기관으로 안내합니다.",
    steps: [
      "증상 관련 위험신호 확인",
      "가정 관찰·일반 정보는 공식 건강정보로 안내",
      "증상이 지속·악화되면 보건소·의료기관 상담 권장",
    ],
  },
  기타: {
    topic: "일반 문의", urgency: "info", urgencyLabel: "일반 정보",
    principle: "질문 주제를 분류해 가장 가까운 공식 정보로 연결합니다.",
    steps: [
      "질문 주제 분류",
      "가장 가까운 공식 정보 안내",
      "필요 시 담당기관 연결",
    ],
  },
};

// 응급/위험신호 체크리스트
const EMERGENCY_CHECKLIST = {
  열: [
    "3개월 미만 영아가 38℃ 이상의 열이 있는 경우",
    "열성 경련을 했거나 의식이 처지는 경우",
    "호흡이 매우 가쁘거나 입술이 파래지는 경우",
    "수분을 거의 섭취하지 못하는 경우",
    "열이 5일 이상 지속되는 경우",
  ],
  호흡: [
    "숨이 가쁘고 갈비뼈가 들어갈 정도로 힘들게 숨을 쉬는 경우",
    "입술·손톱이 파랗게 변하는 경우",
    "쌕쌕거리는 소리가 심하고 점점 악화되는 경우",
  ],
  설사구토: [
    "수분을 전혀 섭취하지 못하는 경우",
    "소변량이 현저히 줄어든 경우 (반나절 이상 기저귀가 마른 경우)",
    "혈변·혈성 구토가 있는 경우",
    "축 처지고 반응이 둔한 경우",
  ],
  발진: [
    "발진과 함께 고열이 동반된 경우",
    "보랏빛 점상출혈이 있는 경우",
    "호흡곤란·얼굴 부종이 동반된 경우",
  ],
};

// ============================================================
// 시설별 특이점 보강 (highlight 태그 + 상세 설명)
// 기존 FACILITIES 객체에 병합 — 시설마다 '왜 여기인지'가 드러나도록
// ============================================================
const FACILITY_EXTRA = {
  1:  { highlight: "도서관·체육·문화 원스톱", description: "도서관·체육관·문화강좌가 한 건물에 모여 있어 날씨와 무관하게 종일 머물 수 있습니다. 1층에 수유실과 유아 휴게공간이 분리되어 있어 영아 동반에 편리합니다." },
  2:  { highlight: "넓은 어린이도서관", description: "어린이도서관과 다목적실이 넓어 우천·폭염 시 장시간 머물기 좋습니다. 다만 주말 오후에는 이용자가 몰리는 편입니다." },
  3:  { highlight: "장난감도서관 연계", description: "같은 생활권의 장난감도서관과 연계해 장난감 대여 후 실내 놀이까지 이어가기 좋습니다." },
  4:  { highlight: "넓은 광장 + 실내", description: "넓은 실내 공간과 야외 광장을 모두 갖춰 날씨와 상관없이 활동 폭이 넓습니다. 주차 규모가 커 차량 이용이 편합니다." },
  5:  { highlight: "공동육아나눔터 병설", description: "건물 안에서 공동육아나눔터를 함께 이용할 수 있어 또래 모임과 실내 놀이를 한 곳에서 해결할 수 있습니다." },
  6:  { highlight: "최신 시설·청결", description: "최근 개관해 수유실·기저귀 교환대 등 영유아 편의시설 상태가 특히 양호합니다." },
  7:  { highlight: "차분한 분위기", description: "이용자가 비교적 적어 어린 영아를 데리고도 차분하게 머물 수 있습니다." },
  8:  { highlight: "한산해 첫 외출 적합", description: "평일·주말 모두 한산한 편이라 첫 외출이나 어린 영아 동반에 부담이 적습니다." },
  9:  { highlight: "영유아 가구 밀집지", description: "신규 입주지역에 있어 또래 가족을 만나기 쉽고 영아 전용 공간이 마련되어 있습니다." },
  10: { highlight: "광폭 유모차 사전확인", description: "초기 조성지역으로 출입 동선이 다소 좁아 광폭·쌍둥이 유모차는 사전 확인을 권장합니다. 실내 주차는 어렵습니다." },
  11: { highlight: "영유아 전용 분리공간", description: "영유아 전용실과 그림책 구역이 분리되어 있어 소리에 민감한 영아도 조용히 머물 수 있습니다." },
  12: { highlight: "그림책 읽기 프로그램", description: "정기 그림책 읽기·구연 프로그램을 운영해 12개월 이상 아이의 첫 도서관 경험에 좋습니다." },
  13: { highlight: "넓은 영유아 공간", description: "영유아 공간이 넓고 그림책 보유량이 많아 형제·쌍둥이 동반에도 여유롭습니다." },
  14: { highlight: "국립·대형 어린이자료실", description: "국립도서관의 대규모 어린이자료실로 장서가 풍부합니다. 세종시 직접 관리 시설은 아니며, 둘째·넷째 월요일 휴관이니 공식 페이지로 확인하세요. (6개월 이상 권장)" },
  15: { highlight: "예약제 또래모임", description: "예약제로 운영되며 보호자 교류 프로그램이 활발합니다. 평일 낮 영아 또래모임을 찾는 가정에 적합합니다." },
  16: { highlight: "그림책·모래놀이", description: "그림책 읽기, 모래놀이 등 오감 놀이 프로그램을 정기 운영합니다. (예약 필요)" },
  17: { highlight: "보람 생활권 모임", description: "보람동 인근 가정 이용이 많아 같은 생활권 또래를 만나기 좋습니다. (예약 필요)" },
  18: { highlight: "영아 전용공간 신설", description: "최근 개관해 영아 전용 공간이 별도로 마련되어 어린 월령도 안전하게 이용할 수 있습니다. (예약 필요)" },
  19: { highlight: "부모교육·시간제돌봄", description: "부모교육, 다문화·한부모 지원, 시간제 돌봄 등 가족 단위 프로그램의 중심 기관입니다. 실내 주차는 제한적입니다. (예약 필요)" },
  20: { highlight: "시간제보육·장난감대여 거점", description: "시간제보육·장난감 대여·부모교육을 제공하는 영유아 지원의 핵심 기관입니다. 시간제보육을 찾는다면 가장 먼저 확인하세요. (예약 필요)" },
  21: { highlight: "체험형 전시 풍부", description: "국립 체험형 어린이박물관으로 오감 전시가 풍부합니다. 사전 예약 필수이며 세종시 직접 관리 시설은 아닙니다. (12개월 이상 권장)" },
  22: { highlight: "기록 테마 체험", description: "기록을 주제로 한 체험 공간으로 걷기 시작한 유아에게 적합합니다. 월요일 휴관·예약제이며 국가기록원 운영 시설입니다. (18개월 이상 권장)" },
  23: { highlight: "평탄한 유모차 산책로", description: "호수를 따라 평탄한 산책로가 길게 이어져 유모차 이동이 편합니다. 그늘·실내가 적어 우천·폭염·미세먼지 나쁨 시에는 비추천입니다." },
  24: { highlight: "넓은 잔디밭", description: "넓은 잔디밭과 산책로가 있어 걷기 시작한 아이의 야외 활동에 좋습니다. 그늘이 부족해 한낮 폭염 시에는 비추천입니다." },
  25: { highlight: "실내 온실 보유", description: "대형 실내 온실이 있어 우천·폭염 시에도 일부 관람이 가능합니다. 영유아는 무료(성인 유료)이며 국립 시설로 공식 안내를 따릅니다." },
  26: { highlight: "영유아검진·예방접종", description: "영유아검진과 예방접종 등 모자보건 서비스를 제공합니다. 건강·접종 문의의 1차 공식 창구입니다. (평일 운영, 예약 권장)" },
  27: { highlight: "0~24개월 영아모임", description: "0~24개월 영아 보호자 모임이 특히 활발합니다. (예약 필요)" },
  28: { highlight: "장난감도서관 인접", description: "장난감도서관이 인접해 장난감 대여와 그림책 독서를 함께 즐기기 좋습니다." },
  29: { highlight: "주중 오전 영아모임", description: "주중 오전 영아 보호자 프로그램을 운영합니다. (예약 필요)" },
  30: { highlight: "장난감 대여 전문", description: "다양한 장난감을 대여할 수 있는 전문 공간입니다. 회원가입 후 이용하며, 비싼 교구를 사기 전 체험해 보기 좋습니다. (예약 필요)" },
};

// 병합: 기존 description을 더 구체적인 설명으로 교체하고 highlight 태그 부여
FACILITIES.forEach(f => {
  const ex = FACILITY_EXTRA[f.id];
  if (!ex) return;
  if (ex.highlight) f.highlight = ex.highlight;
  if (ex.description) f.description = ex.description;
});
